#!/usr/bin/env bash

basedir="$(cd "$(dirname "$0")/.." && pwd)"

find "${basedir}/gitignore/templates" \
  -type f \
  -name '*.gitignore' |
  while read -r file; do
    name="${file##*/}"
    name="${name%.gitignore}"
    key="${name,,}"

    {

      cat - "$file" <<EOM
# -*- mode: snippet -*-
# name: ${name}
# contributor: Toptal & contributors
# key: ${key}
# --

### ${name} ###

EOM
    } >"${basedir}/snippets/gitignore-mode/${key}"
  done
